/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package jaboc_UI.jabocUI_Cardapio;

import jaboc_Biblioteca.glasspanepopup.GlassPanePopup;
import java.awt.Color;
import java.awt.Dimension;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.geom.RoundRectangle2D;
import javax.swing.JScrollBar;
import jaboc_Biblioteca.outras.ModernScrollBarUI;
import net.miginfocom.swing.MigLayout;

/**
 *
 * @author eeuar
 */
public class interface_Carrinho extends javax.swing.JPanel {

    /**
     * Creates new form interface_carrinho
     */
    public interface_Carrinho() {
        initComponents();
        setOpaque(false);
        JScrollBar bar = scrollCarrinho.getVerticalScrollBar();
        bar.setOpaque(false);
        bar.setForeground(new Color(79, 84, 101));
        bar.setPreferredSize(new Dimension(8, 5));
        bar.setUI(new ModernScrollBarUI());
        
        panelCarrinho.setLayout(new MigLayout("inset 0, fillx, wrap", "[fill]"));
        addCarrinho();
    }

    private void addCarrinho() {
        panelCarrinho.add(new interface_itemCarrinho("Pão", "Descrição"));
        panelCarrinho.add(new interface_itemCarrinho("ProdutoX", "Descrição"));
        panelCarrinho.add(new interface_itemCarrinho("ProdutoX", "Descrição"));
         panelCarrinho.add(new interface_itemCarrinho("ProdutoX", "Descrição"));
    }

    protected void paintComponent(Graphics g) {
        Graphics2D g2 = (Graphics2D) g.create();
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        g2.fill(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 20, 20));
        g2.dispose();
        super.paintComponent(g); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bPopUp = new jaboc_UI.jabocUI_Utilidades.ButtonCirculo();
        panel1 = new jaboc_UI.jabocUI_Utilidades.Panel();
        carrinhotxt = new javax.swing.JLabel();
        bPopUpExit = new jaboc_UI.jabocUI_Utilidades.ButtonCirculo();
        panelP = new jaboc_UI.jabocUI_Utilidades.Panel();
        scrollCarrinho = new javax.swing.JScrollPane();
        panelCarrinho = new javax.swing.JPanel();

        bPopUp.setBackground(new java.awt.Color(250, 112, 112));
        bPopUp.setForeground(new java.awt.Color(255, 255, 255));
        bPopUp.setText("X");

        panel1.setBackground(new java.awt.Color(255, 255, 255));

        carrinhotxt.setBackground(new java.awt.Color(79, 84, 101));
        carrinhotxt.setFont(new java.awt.Font("Gill Sans MT", 1, 20)); // NOI18N
        carrinhotxt.setForeground(new java.awt.Color(79, 84, 101));
        carrinhotxt.setText("Carrinho");

        bPopUpExit.setBackground(new java.awt.Color(250, 112, 112));
        bPopUpExit.setForeground(new java.awt.Color(255, 255, 255));
        bPopUpExit.setText("X");
        bPopUpExit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bPopUpExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPopUpExitActionPerformed(evt);
            }
        });

        panelP.setBackground(new java.awt.Color(255, 204, 204));

        scrollCarrinho.setBorder(null);
        scrollCarrinho.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        panelCarrinho.setBackground(new java.awt.Color(255, 204, 204));

        javax.swing.GroupLayout panelCarrinhoLayout = new javax.swing.GroupLayout(panelCarrinho);
        panelCarrinho.setLayout(panelCarrinhoLayout);
        panelCarrinhoLayout.setHorizontalGroup(
            panelCarrinhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 453, Short.MAX_VALUE)
        );
        panelCarrinhoLayout.setVerticalGroup(
            panelCarrinhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 474, Short.MAX_VALUE)
        );

        scrollCarrinho.setViewportView(panelCarrinho);

        javax.swing.GroupLayout panelPLayout = new javax.swing.GroupLayout(panelP);
        panelP.setLayout(panelPLayout);
        panelPLayout.setHorizontalGroup(
            panelPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollCarrinho, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelPLayout.setVerticalGroup(
            panelPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollCarrinho, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(carrinhotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 359, Short.MAX_VALUE)
                        .addComponent(bPopUpExit, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(carrinhotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bPopUpExit, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bPopUpExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPopUpExitActionPerformed
        GlassPanePopup.closePopupLast();
    }//GEN-LAST:event_bPopUpExitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private jaboc_UI.jabocUI_Utilidades.ButtonCirculo bPopUp;
    private jaboc_UI.jabocUI_Utilidades.ButtonCirculo bPopUpExit;
    private javax.swing.JLabel carrinhotxt;
    private jaboc_UI.jabocUI_Utilidades.Panel panel1;
    private javax.swing.JPanel panelCarrinho;
    private jaboc_UI.jabocUI_Utilidades.Panel panelP;
    private javax.swing.JScrollPane scrollCarrinho;
    // End of variables declaration//GEN-END:variables
}
