/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jaboc_UI.Clientes;

import jaboc_BancoDeDados.Controle.Logavel;
import jaboc_BancoDeDados.Modelo.DAO_ContaCliente;
import jaboc_Classes.Login;
import jaboc_UI.Cardapio.interface_Cardapio;
import jaboc_UI.JabocUI_Utilidades.JabocUI_popUp.PopUp_vazio;
import java.awt.Color;
import raven.glasspanepopup.GlassPanePopup;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JTextField;

/**
 *
 * @author eeuar
 */
public class interface_loginCliente extends javax.swing.JFrame {
    private final ArrayList<JTextField> CAMPOS_TEXTO = new ArrayList<>();
    private final ArrayList<String> DADOS_CAMPOS_TEXTO = new ArrayList<>();
    private boolean activeBOlho_senha = false;
    /**
     * Creates new form interface_loginCliente
     */
    public interface_loginCliente() {
        initComponents();
        setLocationRelativeTo(null);
        GlassPanePopup.install(this);
        
        cpfCliente_login.addFormatacao("###.###.###-##");
        
        this.armazenaCamposTextos();
        this.armazenaDadosCamposTextos();
    }
    
    public interface_loginCliente(String cpfCliente) {
        initComponents();
        setLocationRelativeTo(null);
        GlassPanePopup.install(this);
        
        this.cpfCliente_login.addFormatacao("###.###.###-##");       
        
        this.armazenaCamposTextos();
        this.armazenaDadosCamposTextos();
        
        this.cpfCliente_login.setText(cpfCliente);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        bVoltar = new jaboc_UI.jabocUI_Utilidades.ButtonCirculo();
        loginCliente = new jaboc_UI.jabocUI_Utilidades.ButtonCirculo();
        jLabel1 = new javax.swing.JLabel();
        panel1 = new jaboc_UI.jabocUI_Utilidades.Panel();
        panel5 = new jaboc_UI.jabocUI_Utilidades.Panel();
        icpf = new javax.swing.JLabel();
        cpfCliente_login = new jaboc_UI.JabocUI_Utilidades.JabocUI_Classes.FormattedTextField();
        panel11 = new jaboc_UI.jabocUI_Utilidades.Panel();
        senhaCliente_login = new jaboc_UI.jabocUI_Utilidades.PasswordField();
        isenha3 = new javax.swing.JLabel();
        bOlho_senha = new jaboc_UI.jabocUI_Utilidades.ButtonCirculo();
        panel3 = new jaboc_UI.jabocUI_Utilidades.Panel();
        jLabel6 = new javax.swing.JLabel();
        loginAcess = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(164, 144, 124));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(252, 252, 252));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/principal/logo4.png"))); // NOI18N
        jLabel11.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        bVoltar.setBackground(new java.awt.Color(252, 252, 252));
        bVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons/i_back.png"))); // NOI18N
        bVoltar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bVoltarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bVoltarMouseExited(evt);
            }
        });
        bVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVoltarActionPerformed(evt);
            }
        });

        loginCliente.setBackground(new java.awt.Color(79, 84, 101));
        loginCliente.setForeground(new java.awt.Color(255, 255, 255));
        loginCliente.setText("Entrar");
        loginCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 170, Short.MAX_VALUE)
                .addComponent(bVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(loginCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(loginCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 0, -1, 550));

        jLabel1.setFont(new java.awt.Font("Gill Sans MT", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LOGIN");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 93, 404, 80));

        panel1.setBackground(new java.awt.Color(141, 123, 104));

        panel5.setBackground(new java.awt.Color(255, 255, 255));

        icpf.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icpf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconLabel/cpf.png"))); // NOI18N

        cpfCliente_login.setText(" CPF:");

        javax.swing.GroupLayout panel5Layout = new javax.swing.GroupLayout(panel5);
        panel5.setLayout(panel5Layout);
        panel5Layout.setHorizontalGroup(
            panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(icpf, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(cpfCliente_login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel5Layout.setVerticalGroup(
            panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel5Layout.createSequentialGroup()
                .addGroup(panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(icpf, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cpfCliente_login, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panel11.setBackground(new java.awt.Color(255, 255, 255));

        senhaCliente_login.setText(" Senha:");
        senhaCliente_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senhaCliente_loginActionPerformed(evt);
            }
        });

        isenha3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        isenha3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconLabel/senha.png"))); // NOI18N

        javax.swing.GroupLayout panel11Layout = new javax.swing.GroupLayout(panel11);
        panel11.setLayout(panel11Layout);
        panel11Layout.setHorizontalGroup(
            panel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(isenha3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(senhaCliente_login, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel11Layout.setVerticalGroup(
            panel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel11Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(panel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(senhaCliente_login, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(isenha3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        bOlho_senha.setBackground(new java.awt.Color(252, 252, 252));
        bOlho_senha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconLabel/olho.png"))); // NOI18N
        bOlho_senha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bOlho_senhaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(panel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(panel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bOlho_senha, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(panel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bOlho_senha, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel1.add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 217, -1, -1));

        panel3.setBackground(new java.awt.Color(252, 252, 252));
        panel3.setForeground(new java.awt.Color(255, 255, 255));

        jLabel6.setBackground(new java.awt.Color(79, 84, 101));
        jLabel6.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(79, 84, 101));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Quer criar uma conta?");

        loginAcess.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        loginAcess.setForeground(new java.awt.Color(154, 53, 255));
        loginAcess.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        loginAcess.setText("Clique aqui");
        loginAcess.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginAcess.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginAcessMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginAcessMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                loginAcessMousePressed(evt);
            }
        });

        javax.swing.GroupLayout panel3Layout = new javax.swing.GroupLayout(panel3);
        panel3.setLayout(panel3Layout);
        panel3Layout.setHorizontalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loginAcess, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );
        panel3Layout.setVerticalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                    .addComponent(loginAcess))
                .addContainerGap())
        );

        jPanel1.add(panel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 391, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/principal/fdn1.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 550));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bVoltarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bVoltarMouseEntered
        bVoltar.setBackground(new Color(237, 237, 237));
    }//GEN-LAST:event_bVoltarMouseEntered

    private void bVoltarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bVoltarMouseExited
        bVoltar.setBackground(new Color(252, 252, 252));
    }//GEN-LAST:event_bVoltarMouseExited

    private void bVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVoltarActionPerformed
        interface_menuCliente i_menuCliente = new interface_menuCliente();
        i_menuCliente.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bVoltarActionPerformed

    private void loginAcessMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginAcessMouseClicked
        interface_criarCliente i_cCliente = new interface_criarCliente();
        i_cCliente.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_loginAcessMouseClicked

    private void loginAcessMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginAcessMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_loginAcessMouseEntered

    private void loginAcessMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginAcessMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginAcessMousePressed

    private void senhaCliente_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senhaCliente_loginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_senhaCliente_loginActionPerformed

    private void cpfCliente_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpfCliente_loginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpfCliente_loginActionPerformed

    private void loginClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginClienteActionPerformed
         if(this.camposPreenchidos()){
            String cpfLogin = cpfCliente_login.getText();          
            String senhaLogin = String.valueOf(senhaCliente_login.getPassword());
            Logavel buscandoLoginBD = new DAO_ContaCliente(); 

            Login clienteLogando = new Login(cpfLogin, senhaLogin);
            if(buscandoLoginBD.existeCpf(clienteLogando.getCPF())){
            
                if(buscandoLoginBD.login(clienteLogando)){
                    interface_Cardapio iCardapio = new interface_Cardapio();                
                    iCardapio.setVisible(true);
                    this.dispose();                       
                }else{
                    senhaCliente_login.setText(" Senha:");
                    senhaCliente_login.setEchoChar((char) 0);
                } 
                
            }else{
                this.setarCamposVazios();
            }    
        }else{
            GlassPanePopup.showPopup(new PopUp_vazio());
        }
    }//GEN-LAST:event_loginClienteActionPerformed

    private void bOlho_senhaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bOlho_senhaMouseClicked
        String senha = String.valueOf(this.senhaCliente_login.getPassword());
        if(this.activeBOlho_senha && !senha.equals(" Senha")){
            this.senhaCliente_login.setEchoChar('*');
            this.bOlho_senha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconLabel/olho-cruzado.png")));
            this.activeBOlho_senha = false;
        }else if(this.activeBOlho_senha == false && !senha.equals(" Senha")){
            this.senhaCliente_login.setEchoChar((char) 0);
            this.bOlho_senha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconLabel/olho.png")));
            this.activeBOlho_senha = true;
        }
    }//GEN-LAST:event_bOlho_senhaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interface_loginCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interface_loginCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interface_loginCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interface_loginCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new interface_loginCliente().setVisible(true);
            }
        });
    }

    private void armazenaCamposTextos(){
        this.CAMPOS_TEXTO.add(cpfCliente_login);
        this.CAMPOS_TEXTO.add(senhaCliente_login);
    }
    
    private void armazenaDadosCamposTextos(){
        this.DADOS_CAMPOS_TEXTO.add(cpfCliente_login.getText());
        this.DADOS_CAMPOS_TEXTO.add(String.valueOf(senhaCliente_login.getPassword()));
    }   
    
   private boolean camposPreenchidos(){
       Iterator<JTextField> percorrerCamposTextos = this.CAMPOS_TEXTO.iterator();
       Iterator<String> percorrerDados_CamposTextos = this.DADOS_CAMPOS_TEXTO.iterator();
       
       while(percorrerCamposTextos.hasNext()){
           JTextField campoAtual = percorrerCamposTextos.next();
           String dadoCampoTexto = percorrerDados_CamposTextos.next();
           
           if(campoAtual.getText().equals(dadoCampoTexto)){
               return false;
           }
       }
       
       return true;
   }
   
   private void setarCamposVazios(){
       System.out.println(this.DADOS_CAMPOS_TEXTO);
        Iterator<JTextField> percorrerCamposTextos = this.CAMPOS_TEXTO.iterator();
        Iterator<String> percorrerDados_CamposTextos = this.DADOS_CAMPOS_TEXTO.iterator();
       
        while(percorrerCamposTextos.hasNext()){
           JTextField campoAtual = percorrerCamposTextos.next();
           String novoDadoCampoAtual = percorrerDados_CamposTextos.next();
           
           campoAtual.setText(novoDadoCampoAtual);
       }
        
        senhaCliente_login.setEchoChar((char)0);
   }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private jaboc_UI.jabocUI_Utilidades.ButtonCirculo bOlho_senha;
    private jaboc_UI.jabocUI_Utilidades.ButtonCirculo bVoltar;
    private jaboc_UI.JabocUI_Utilidades.JabocUI_Classes.FormattedTextField cpfCliente_login;
    private javax.swing.JLabel icpf;
    private javax.swing.JLabel isenha3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel loginAcess;
    private jaboc_UI.jabocUI_Utilidades.ButtonCirculo loginCliente;
    private jaboc_UI.jabocUI_Utilidades.Panel panel1;
    private jaboc_UI.jabocUI_Utilidades.Panel panel11;
    private jaboc_UI.jabocUI_Utilidades.Panel panel3;
    private jaboc_UI.jabocUI_Utilidades.Panel panel5;
    private jaboc_UI.jabocUI_Utilidades.PasswordField senhaCliente_login;
    // End of variables declaration//GEN-END:variables
}
