package jaboc_UI.Clientes;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.awt.Color;
import javax.swing.JTextField;
import jaboc_Biblioteca.glasspanepopup.GlassPanePopup;
import jaboc_Classes.Conta_Cliente;
import jaboc_BancoDeDados.Modelo.DAO_ContaCliente;
import jaboc_BancoDeDados.Modelo.DAO_ContaFuncionario;
import jaboc_BancoDeDados.Modelo.DAO_Pessoa;
import jaboc_Classes.Pessoa;
import jaboc_UI.Cardapio.interface_Cardapio;
import jaboc_UI.JabocUI_Utilidades.JabocUI_popUp.PopUp_FuncionarioParaCliente;
import jaboc_UI.jabocUI_Utilidades.PopUp_CampoVazio;
import java.util.ArrayList;
import java.util.Iterator;
/**
 *
 * @author guilh
 */
public class interface_criarCliente extends javax.swing.JFrame {
    
    private ArrayList<JTextField> camposTexto =  new ArrayList<>();
    private ArrayList<String> dados_camposTexto =  new ArrayList<>();
    private boolean activeButton = true, activeButton1 = true;
    /**
     * Creates new form interfaceCliente
     */
    public interface_criarCliente() {
        initComponents();
        setLocationRelativeTo(null);
        GlassPanePopup.install(this);
        
        cpfCliente_cadastrar.addFormatacao("###.###.###-##");
        telefoneCliente_cadastrar.addFormatacao("(##) #####-####");
        
        this.armazenaCamposTextos();
        this.armazenaDadosCamposTextos();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        aaa = new jaboc_UI.jabocUI_Utilidades.TextField();
        textField2 = new jaboc_UI.jabocUI_Utilidades.TextField();
        textField3 = new jaboc_UI.jabocUI_Utilidades.TextField();
        textField4 = new jaboc_UI.jabocUI_Utilidades.TextField();
        textField5 = new jaboc_UI.jabocUI_Utilidades.TextField();
        textField6 = new jaboc_UI.jabocUI_Utilidades.TextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        bVoltar = new jaboc_UI.jabocUI_Utilidades.ButtonCirculo();
        SingUp = new jaboc_UI.jabocUI_Utilidades.ButtonCirculo();
        jLabel5 = new javax.swing.JLabel();
        panel1 = new jaboc_UI.jabocUI_Utilidades.Panel();
        panel4 = new jaboc_UI.jabocUI_Utilidades.Panel();
        nomeCliente_cadastrar = new jaboc_UI.jabocUI_Utilidades.TextField();
        iuser = new javax.swing.JLabel();
        panel5 = new jaboc_UI.jabocUI_Utilidades.Panel();
        icpf = new javax.swing.JLabel();
        cpfCliente_cadastrar = new jaboc_UI.JabocUI_Utilidades.JabocUI_Classes.FormattedTextField();
        panel6 = new jaboc_UI.jabocUI_Utilidades.Panel();
        itel = new javax.swing.JLabel();
        telefoneCliente_cadastrar = new jaboc_UI.JabocUI_Utilidades.JabocUI_Classes.FormattedTextField();
        panel7 = new jaboc_UI.jabocUI_Utilidades.Panel();
        enderecoCliente_cadastrar = new jaboc_UI.jabocUI_Utilidades.TextField();
        itel2 = new javax.swing.JLabel();
        panel2 = new jaboc_UI.jabocUI_Utilidades.Panel();
        panel8 = new jaboc_UI.jabocUI_Utilidades.Panel();
        senhaCliente_cadastrar = new jaboc_UI.jabocUI_Utilidades.PasswordField();
        isenha = new javax.swing.JLabel();
        panel9 = new jaboc_UI.jabocUI_Utilidades.Panel();
        verificarSenhaCliente_cadastrar = new jaboc_UI.jabocUI_Utilidades.PasswordField();
        isenha2 = new javax.swing.JLabel();
        bOlho = new jaboc_UI.jabocUI_Utilidades.ButtonCirculo();
        bOlho1 = new jaboc_UI.jabocUI_Utilidades.ButtonCirculo();
        panel3 = new jaboc_UI.jabocUI_Utilidades.Panel();
        jLabel6 = new javax.swing.JLabel();
        loginAcess = new javax.swing.JLabel();

        jLabel8.setText("jLabel8");

        jLabel1.setText("jLabel1");

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(164, 144, 124));
        jPanel1.setPreferredSize(new java.awt.Dimension(850, 510));

        jPanel3.setBackground(new java.awt.Color(252, 252, 252));

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo4.png"))); // NOI18N
        jLabel11.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        bVoltar.setBackground(new java.awt.Color(252, 252, 252));
        bVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons/i_back.png"))); // NOI18N
        bVoltar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bVoltarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bVoltarMouseExited(evt);
            }
        });
        bVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVoltarActionPerformed(evt);
            }
        });

        SingUp.setBackground(new java.awt.Color(79, 84, 101));
        SingUp.setForeground(new java.awt.Color(252, 252, 252));
        SingUp.setText("Cadastrar");
        SingUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SingUpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SingUpMouseExited(evt);
            }
        });
        SingUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SingUpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(SingUp, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SingUp, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        SingUp.getAccessibleContext().setAccessibleName("Criar conta");

        jLabel5.setFont(new java.awt.Font("Gill Sans MT", 1, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons/i_user.png"))); // NOI18N
        jLabel5.setText(" CRIAR CONTA");

        panel1.setBackground(new java.awt.Color(141, 123, 104));

        panel4.setBackground(new java.awt.Color(255, 255, 255));

        nomeCliente_cadastrar.setText(" Nome:");
        nomeCliente_cadastrar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                nomeCliente_cadastrarFocusLost(evt);
            }
        });
        nomeCliente_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeCliente_cadastrarActionPerformed(evt);
            }
        });

        iuser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iuser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconLabel/user.png"))); // NOI18N

        javax.swing.GroupLayout panel4Layout = new javax.swing.GroupLayout(panel4);
        panel4.setLayout(panel4Layout);
        panel4Layout.setHorizontalGroup(
            panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(iuser, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(nomeCliente_cadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel4Layout.setVerticalGroup(
            panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel4Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(iuser, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(nomeCliente_cadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel5.setBackground(new java.awt.Color(255, 255, 255));

        icpf.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icpf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconLabel/cpf.png"))); // NOI18N

        cpfCliente_cadastrar.setText(" CPF:");

        javax.swing.GroupLayout panel5Layout = new javax.swing.GroupLayout(panel5);
        panel5.setLayout(panel5Layout);
        panel5Layout.setHorizontalGroup(
            panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(icpf, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(cpfCliente_cadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel5Layout.setVerticalGroup(
            panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(icpf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panel5Layout.createSequentialGroup()
                .addComponent(cpfCliente_cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panel6.setBackground(new java.awt.Color(255, 255, 255));

        itel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        itel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconLabel/tel.png"))); // NOI18N

        telefoneCliente_cadastrar.setText(" Telefone:");
        telefoneCliente_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefoneCliente_cadastrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel6Layout = new javax.swing.GroupLayout(panel6);
        panel6.setLayout(panel6Layout);
        panel6Layout.setHorizontalGroup(
            panel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(itel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(telefoneCliente_cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panel6Layout.setVerticalGroup(
            panel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel6Layout.createSequentialGroup()
                .addGroup(panel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(itel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telefoneCliente_cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panel7.setBackground(new java.awt.Color(255, 255, 255));

        enderecoCliente_cadastrar.setText(" Endereço:");

        itel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        itel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconLabel/casa.png"))); // NOI18N

        javax.swing.GroupLayout panel7Layout = new javax.swing.GroupLayout(panel7);
        panel7.setLayout(panel7Layout);
        panel7Layout.setHorizontalGroup(
            panel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(itel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(enderecoCliente_cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panel7Layout.setVerticalGroup(
            panel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel7Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(panel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(enderecoCliente_cadastrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addComponent(panel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(panel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(panel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(panel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(panel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        panel2.setBackground(new java.awt.Color(141, 123, 104));

        panel8.setBackground(new java.awt.Color(255, 255, 255));

        senhaCliente_cadastrar.setText(" Senha:");
        senhaCliente_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senhaCliente_cadastrarActionPerformed(evt);
            }
        });

        isenha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        isenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconLabel/senha.png"))); // NOI18N

        javax.swing.GroupLayout panel8Layout = new javax.swing.GroupLayout(panel8);
        panel8.setLayout(panel8Layout);
        panel8Layout.setHorizontalGroup(
            panel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(isenha, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(senhaCliente_cadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel8Layout.setVerticalGroup(
            panel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(panel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(senhaCliente_cadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(isenha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        panel9.setBackground(new java.awt.Color(255, 255, 255));

        verificarSenhaCliente_cadastrar.setText(" Repita a senha:");

        isenha2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        isenha2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconLabel/senha.png"))); // NOI18N

        javax.swing.GroupLayout panel9Layout = new javax.swing.GroupLayout(panel9);
        panel9.setLayout(panel9Layout);
        panel9Layout.setHorizontalGroup(
            panel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(isenha2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(verificarSenhaCliente_cadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel9Layout.setVerticalGroup(
            panel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel9Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(verificarSenhaCliente_cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(isenha2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        bOlho.setBackground(new java.awt.Color(252, 252, 252));
        bOlho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconLabel/olho.png"))); // NOI18N
        bOlho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bOlhoMouseClicked(evt);
            }
        });
        bOlho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bOlhoActionPerformed(evt);
            }
        });

        bOlho1.setBackground(new java.awt.Color(252, 252, 252));
        bOlho1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconLabel/olho.png"))); // NOI18N
        bOlho1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bOlho1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bOlho, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bOlho1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bOlho, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bOlho1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        panel3.setBackground(new java.awt.Color(252, 252, 252));

        jLabel6.setBackground(new java.awt.Color(79, 84, 101));
        jLabel6.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(79, 84, 101));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Já tem uma conta?");

        loginAcess.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        loginAcess.setForeground(new java.awt.Color(154, 53, 255));
        loginAcess.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        loginAcess.setText("Clique aqui");
        loginAcess.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginAcess.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginAcessMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginAcessMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                loginAcessMousePressed(evt);
            }
        });

        javax.swing.GroupLayout panel3Layout = new javax.swing.GroupLayout(panel3);
        panel3.setLayout(panel3Layout);
        panel3Layout.setHorizontalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loginAcess, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        panel3Layout.setVerticalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                    .addComponent(loginAcess))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 444, Short.MAX_VALUE)
                            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(panel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVoltarActionPerformed
        interface_menuCliente i_menuCliente = new interface_menuCliente();
        i_menuCliente.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bVoltarActionPerformed

    private void bVoltarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bVoltarMouseEntered
        bVoltar.setBackground(new Color(237, 237, 237));
    }//GEN-LAST:event_bVoltarMouseEntered

    private void bVoltarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bVoltarMouseExited
        bVoltar.setBackground(new Color(252, 252, 252));
    }//GEN-LAST:event_bVoltarMouseExited

    private void SingUpActionPerformed(java.awt.event.ActionEvent evt){//GEN-FIRST:event_SingUpActionPerformed
        if(this.camposPreenchidos()){
        
            String senha_criarCliente = String.valueOf(senhaCliente_cadastrar.getPassword());
            String verificarSenha_criarCliente = String.valueOf(verificarSenhaCliente_cadastrar.getPassword());

            if(senha_criarCliente.equals(verificarSenha_criarCliente)){
                String cpf_cadastrarCliente = cpfCliente_cadastrar.getText();
                String nome_cadastrarCliente = nomeCliente_cadastrar.getText();
                String endereco_cadastrarCliente = enderecoCliente_cadastrar.getText();
                String telefone_cadastrarCliente = telefoneCliente_cadastrar.getText();

                Pessoa objetoPessoa = new Pessoa(nome_cadastrarCliente, cpf_cadastrarCliente,
                endereco_cadastrarCliente, telefone_cadastrarCliente); 

                Conta_Cliente cadastrarCliente = new Conta_Cliente(objetoPessoa, senha_criarCliente);

                DAO_Pessoa daoPessoa = new DAO_Pessoa();
                DAO_ContaFuncionario daoFuncionario = new DAO_ContaFuncionario();
                DAO_ContaCliente daoCliente = new DAO_ContaCliente();

                if(daoCliente.existeRegistro(objetoPessoa.getCpf())){
                    
                    interface_loginCliente iLogin_Cliente = new interface_loginCliente();
                    iLogin_Cliente.getCpfCliente_login().setText(objetoPessoa.getCpf());                
                    iLogin_Cliente.setVisible(true);
                    this.dispose();
                    
                }else if(daoFuncionario.existeRegistro(objetoPessoa.getCpf())){

                    PopUp_FuncionarioParaCliente dialogoFunc = new PopUp_FuncionarioParaCliente(this);
                    boolean criarContaCliente = dialogoFunc.getRespostaDialogo();
                    
                    if(criarContaCliente){

                        daoCliente.insert(cadastrarCliente);
                        this.abrirTelaCardapio();
                        
                    }else{
                        this.setarCamposVazios();
                    }
                    
                }else{
                    
                    daoPessoa.insert(objetoPessoa);
                    daoCliente.insert(cadastrarCliente);
                    this.abrirTelaCardapio();
                    
                }   
            }   
        }else{
          GlassPanePopup.showPopup(new PopUp_CampoVazio());
        }    
    }//GEN-LAST:event_SingUpActionPerformed

    private void loginAcessMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginAcessMouseClicked
        interface_loginCliente i_lCliente = new interface_loginCliente();
        i_lCliente.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_loginAcessMouseClicked

    private void loginAcessMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginAcessMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_loginAcessMouseEntered

    private void loginAcessMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginAcessMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginAcessMousePressed

    private void SingUpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SingUpMouseEntered
        SingUp.setBackground(new Color(63,66,73));
    }//GEN-LAST:event_SingUpMouseEntered

    private void SingUpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SingUpMouseExited
        SingUp.setBackground(new Color(79,84,101));
    }//GEN-LAST:event_SingUpMouseExited

    private void nomeCliente_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeCliente_cadastrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeCliente_cadastrarActionPerformed

    private void bOlhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bOlhoActionPerformed
     
    }//GEN-LAST:event_bOlhoActionPerformed

    private void nomeCliente_cadastrarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nomeCliente_cadastrarFocusLost
 
    }//GEN-LAST:event_nomeCliente_cadastrarFocusLost

    private void bOlhoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bOlhoMouseClicked
         if(activeButton &&  !(senhaCliente_cadastrar.getText().equals(" Senha:"))){
           bOlho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconLabel/olho-cruzado.png")));
           senhaCliente_cadastrar.setEchoChar('*');
           activeButton = false;
           
       }else if(activeButton == false &&  !(senhaCliente_cadastrar.getText().equals(" Senha:"))){
           bOlho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconLabel/olho.png")));
           senhaCliente_cadastrar.setEchoChar((char) 0);
           activeButton = true; 
       }
    }//GEN-LAST:event_bOlhoMouseClicked

    private void bOlho1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bOlho1MouseClicked
         if(activeButton1 &&  !(verificarSenhaCliente_cadastrar.getText().equals(" Repita a Senha:"))){
           bOlho1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconLabel/olho-cruzado.png")));
           verificarSenhaCliente_cadastrar.setEchoChar('*');
           activeButton1 = false;
           
       }else if(activeButton1 == false &&  !(verificarSenhaCliente_cadastrar.getText().equals(" Repita a Senha:"))){
           bOlho1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconLabel/olho.png")));
           verificarSenhaCliente_cadastrar.setEchoChar((char) 0);
           activeButton1 = true; 
       }
    }//GEN-LAST:event_bOlho1MouseClicked

    private void senhaCliente_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senhaCliente_cadastrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_senhaCliente_cadastrarActionPerformed

    private void telefoneCliente_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefoneCliente_cadastrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefoneCliente_cadastrarActionPerformed

     private void armazenaCamposTextos(){
        this.camposTexto.add(nomeCliente_cadastrar);
        this.camposTexto.add(telefoneCliente_cadastrar);
        this.camposTexto.add(cpfCliente_cadastrar);
        this.camposTexto.add(enderecoCliente_cadastrar);
        this.camposTexto.add(senhaCliente_cadastrar);
        this.camposTexto.add(verificarSenhaCliente_cadastrar);
    }
    
     private void armazenaDadosCamposTextos(){
        this.dados_camposTexto.add(nomeCliente_cadastrar.getText());
        this.dados_camposTexto.add(telefoneCliente_cadastrar.getText());
        this.dados_camposTexto.add(cpfCliente_cadastrar.getText());
        this.dados_camposTexto.add(enderecoCliente_cadastrar.getText());
        this.dados_camposTexto.add(String.valueOf(senhaCliente_cadastrar.getPassword()));
        this.dados_camposTexto.add(String.valueOf(verificarSenhaCliente_cadastrar.getPassword()));
    }    
    
    private boolean camposPreenchidos(){
        Iterator<JTextField> percorrerCamposTextos =  this.camposTexto.iterator();
        Iterator<String> percorrerDadosCamposTextos =  this.dados_camposTexto.iterator();
        
        while(percorrerCamposTextos.hasNext()){
            JTextField campoAtual = percorrerCamposTextos.next();
            String dadoCampoAtual = percorrerDadosCamposTextos.next();
            if(campoAtual.getText().equals(dadoCampoAtual)){
                return false;
            }
        }
        return true;
    }
    
    private void setarCamposVazios(){
        Iterator<JTextField> percorrerArray =  this.camposTexto.iterator();
        Iterator<String> percorrerDadosCamposTextos =  this.dados_camposTexto.iterator();
        
        while(percorrerArray.hasNext()){
            JTextField campoAtual = percorrerArray.next();
            String novoDadoCampoAtual = percorrerDadosCamposTextos.next();
            
            campoAtual.setText(novoDadoCampoAtual);
        }
    }
    
    private void abrirTelaCardapio(){
        interface_Cardapio iCardapio = new interface_Cardapio();
        iCardapio.setVisible(true);
        this.dispose();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interface_criarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interface_criarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interface_criarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interface_criarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new interface_criarCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private jaboc_UI.jabocUI_Utilidades.ButtonCirculo SingUp;
    private jaboc_UI.jabocUI_Utilidades.TextField aaa;
    private jaboc_UI.jabocUI_Utilidades.ButtonCirculo bOlho;
    private jaboc_UI.jabocUI_Utilidades.ButtonCirculo bOlho1;
    private jaboc_UI.jabocUI_Utilidades.ButtonCirculo bVoltar;
    private jaboc_UI.JabocUI_Utilidades.JabocUI_Classes.FormattedTextField cpfCliente_cadastrar;
    private jaboc_UI.jabocUI_Utilidades.TextField enderecoCliente_cadastrar;
    private javax.swing.JLabel icpf;
    private javax.swing.JLabel isenha;
    private javax.swing.JLabel isenha2;
    private javax.swing.JLabel itel;
    private javax.swing.JLabel itel2;
    private javax.swing.JLabel iuser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel loginAcess;
    private jaboc_UI.jabocUI_Utilidades.TextField nomeCliente_cadastrar;
    private jaboc_UI.jabocUI_Utilidades.Panel panel1;
    private jaboc_UI.jabocUI_Utilidades.Panel panel2;
    private jaboc_UI.jabocUI_Utilidades.Panel panel3;
    private jaboc_UI.jabocUI_Utilidades.Panel panel4;
    private jaboc_UI.jabocUI_Utilidades.Panel panel5;
    private jaboc_UI.jabocUI_Utilidades.Panel panel6;
    private jaboc_UI.jabocUI_Utilidades.Panel panel7;
    private jaboc_UI.jabocUI_Utilidades.Panel panel8;
    private jaboc_UI.jabocUI_Utilidades.Panel panel9;
    private jaboc_UI.jabocUI_Utilidades.PasswordField senhaCliente_cadastrar;
    private jaboc_UI.JabocUI_Utilidades.JabocUI_Classes.FormattedTextField telefoneCliente_cadastrar;
    private jaboc_UI.jabocUI_Utilidades.TextField textField2;
    private jaboc_UI.jabocUI_Utilidades.TextField textField3;
    private jaboc_UI.jabocUI_Utilidades.TextField textField4;
    private jaboc_UI.jabocUI_Utilidades.TextField textField5;
    private jaboc_UI.jabocUI_Utilidades.TextField textField6;
    private jaboc_UI.jabocUI_Utilidades.PasswordField verificarSenhaCliente_cadastrar;
    // End of variables declaration//GEN-END:variables
}
